#!/bin/bash
################################################################################
# Script to handle MIDI restarts
# @complexbits
#
# Invokes midi_restart_osx
#
################################################################################
THIS=`basename $0`

# usage message
usage_msg(){

    printf "\nUsage: $THIS <opts>\n"
    printf "Options include:\n\n"
    printf "\t--help|-h\tThis message\n"
    printf "\t--debug|-d\tDebug mode\n"
    printf "\t--quiet|-q\tQuiet mode\n"
    printf "\t--freq|-f\tFrequency of recurring MIDI restarts, in seconds. Default is to restart only once and then quit. When -f is set, $THIS will continue to restart the MIDI interface until manually stopped.\n"
    exit 0
}

# unset variables if they are set
[[ $DBG ]] && unset DBG
[[ $QUIET ]] && unset QUIET
[[ $FREQ ]] && unset FREQ

# get arguments and set variables
while [[ $# -gt 0 ]]; do
    case $1 in
	--help|-h) usage_msg;;
	--debug|-d) DBG=1; shift 1;;
	--quiet|-q) QUIET=1; shift 1;;
	--freq|-f) FREQ=$2; shift 2;;
	*) usage_msg;;
    esac
done

# print debug messages about settings
[[ $DBG ]] && printf "\nDebug enabled.\n"
[[ $DBG ]] && [[ $QUIET ]] && printf "Quiet mode enabled.\n"
[[ $DBG ]] && [[ $FREQ ]] && printf "Frequency set to $FREQ.\n"

# run the midi restart program according to settings
[[ ! $FREQ ]] && ./midi_restart_osx
while [[ $FREQ ]]; do
    ./midi_restart_osx
    sleep $FREQ
done


exit 0


